language: python

python: 3.3

env:
  matrix:
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pypy # does not come with unittest.mock
    - env: TOX_ENV=py34 # glibc segfault _after_ running the tests

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
